
# This is a basic workflow to help you get started with Actions

name: Deploy  to GCP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: danielr1996/envsubst-action@1.0.0
      with:
        input: template.json
        output: keys.json
      env:
        GMAIL_AUTH: ${{ secrets.GMAIL_AUTH }}
        GMAIL_ADDR: ${{ secrets.GMAIL_ADDR }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}


    - run: cat keys.json
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        env_vars: DB_PASS=${{ secrets.DB_PASS }},DB_USER=${{ secrets.DB_USER }},DB_HOST=${{ secrets.DB_HOST }}
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
