
# This is a basic workflow to help you get started with Actions

name: Deploy  to GCP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update app.yaml
      run: |
        echo "Updating env_variables in app.yaml..."
        sed -i -e "s/DB_PASS:.*/DB_PASS: ${{ secrets.DB_PASS }}/g" app.yaml
        sed -i -e "s/DB_USER:.*/DB_USER: ${{ secrets.DB_USER }}/g" app.yaml
        sed -i -e "s/DB_HOST:.*/DB_HOST: ${{ secrets.DB_HOST }}/g" app.yaml

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
