name: Deploy to App Engine

on:
  push:
    branches:
      - main

env:
  ENV_VAR_NAME1: value1
  ENV_VAR_NAME2: value2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Update app.yaml
      run: |
        echo "Updating env_variables in app.yaml..."
        sed -i -e "s/ENV_VAR_NAME1:.*/ENV_VAR_NAME1: ${{ env.ENV_VAR_NAME1 }}/g" app.yaml
        sed -i -e "s/ENV_VAR_NAME2:.*/ENV_VAR_NAME2: ${{ env.ENV_VAR_NAME2 }}/g" app.yaml
        ...

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v1.1.0
      with:
        project_id: ${{ env.PROJECT_ID }}
